# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import socket
import sys
from threading import Thread
from concurrent.futures import ThreadPoolExecutor

localhost_ip = socket.gethostbyname(socket.gethostname())

class Ui_Form(object):
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 743)
        Form.setWindowIcon(QtGui.QIcon("logo.jpg"))
        Form.setFixedSize(531,743)


        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 511, 711))
        self.widget.setObjectName("widget")


        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")


        self.label_title = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Italic_IV50")
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)


        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Italic_IV50")
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        
        
        self.lineEdit_targetIp = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_targetIp.setObjectName("lineEdit_targetIp")
        self.horizontalLayout.addWidget(self.lineEdit_targetIp)
        
        
        self.pushButton_localhost = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_localhost.setFont(font)
        self.pushButton_localhost.setObjectName("pushButton_localhost")
        self.pushButton_localhost.clicked.connect(self.buttonF_localhost)
        self.horizontalLayout.addWidget(self.pushButton_localhost)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        
        
        self.label_openedPorts = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Italic_IV50")
        font.setPointSize(11)
        self.label_openedPorts.setFont(font)
        self.label_openedPorts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_openedPorts.setObjectName("label_openedPorts")
        self.verticalLayout.addWidget(self.label_openedPorts)
        
        
        self.textEdit_ports = QtWidgets.QTextEdit(self.widget)
        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Text, QtCore.Qt.red)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.textEdit_ports.setPalette(palette)
        self.textEdit_ports.setFont(font)
        self.textEdit_ports.setObjectName("textEdit_ports")
        self.textEdit_ports.setReadOnly(True)
        self.verticalLayout.addWidget(self.textEdit_ports)
    
        
        self.label_status = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Italic_IV50")
        font.setPointSize(9)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        
        
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        
        self.pushButton_quickScan = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quickScan.setFont(font)
        self.pushButton_quickScan.setObjectName("pushButton_quickScan")
        self.pushButton_quickScan.clicked.connect(self.threadPoolStarter)
        self.horizontalLayout_2.addWidget(self.pushButton_quickScan)
        
        
        self.pushButton_deepScan = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_deepScan.setFont(font)
        self.pushButton_deepScan.setObjectName("pushButton_deepScan")
        self.horizontalLayout_2.addWidget(self.pushButton_deepScan)
        
        
        #self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        #font = QtGui.QFont()
        #font.setBold(True)
        #font.setWeight(75)
        #self.pushButton_cancel.setFont(font)
        #self.pushButton_cancel.setObjectName("pushButton_cancel")
        #self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        
        
        self.pushButton_clear = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_clear.clicked.connect(self.buttonF_clear)
        self.horizontalLayout_2.addWidget(self.pushButton_clear)
        
        
        self.pushButton_quit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_quit.clicked.connect(self.buttonF_quit)
        self.horizontalLayout_2.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PORT SCANNER"))
        self.label_title.setText(_translate("Form", "PORT SCANNER"))
        self.label_2.setText(_translate("Form", "TARGET IP:"))
        self.pushButton_localhost.setText(_translate("Form", "LOCALHOST"))
        self.label_openedPorts.setText(_translate("Form", "OPENED PORTS"))
        self.label_status.setText(_translate("Form", "STATUS"))
        self.pushButton_quickScan.setText(_translate("Form", "QUICK SCAN"))
        self.pushButton_deepScan.setText(_translate("Form", "DEEP SCAN"))
        #self.pushButton_cancel.setText(_translate("Form", "CANCEL"))
        self.pushButton_clear.setText(_translate("Form", "CLEAR"))
        self.pushButton_quit.setText(_translate("Form", "QUIT"))

    def buttonF_quickScan(self):
        pass

    def buttonF_deepScan(self):
        pass

    def buttonF_clear(self):
        self.textEdit_ports.clear()
        self.lineEdit_targetIp.clear()
    
    def buttonF_quit(self):
        self.pool.shutdown(wait=False,cancel_futures=True)
        Form.close()
        sys.exit()

    def buttonF_localhost(self):
        local_ip = socket.gethostbyname(socket.gethostname())
        self.lineEdit_targetIp.setText(local_ip)
    

    def portScanner(self,start,stop):
        try:
            for port in range(start,stop+1):
                S = socket.socket()
                val = S.connect_ex((self.lineEdit_targetIp.text(),port))
                socket.setdefaulttimeout(0.1)
                if (val == 0):
                    self.textEdit_ports.append(f"PORT  {port}  is  OPEN!")
                return port
        except Exception as E:
            self.textEdit_ports.append(E)

    def portScannerS(self,start,stop):
        try:
            for port in range(start,stop+1):
                S = socket.socket()
                val = S.connect_ex((self.lineEdit_targetIp.text(),port))
                socket.setdefaulttimeout(0.1)
                if (val == 0):
                    self.textEdit_ports.append(f"PORT  {port}  is  OPEN!")
                self.progressBar.setProperty("value",port/41)
        except Exception as E:
            self.textEdit_ports.append(E)

    def threadPoolStarter(self):
        self.pool = ThreadPoolExecutor(16)

        w1 = self.pool.submit(self.portScannerS,1,4100)
        w2 = self.pool.submit(self.portScanner,4100,8200)
        w3 = self.pool.submit(self.portScanner,8200,12300)
        w4 = self.pool.submit(self.portScanner,12300,16400)

        w5 = self.pool.submit(self.portScanner,16400,20500)
        w6 = self.pool.submit(self.portScanner,20500,24600)
        w7 = self.pool.submit(self.portScanner,24600,28700)
        w8 = self.pool.submit(self.portScanner,28700,32800)

        w9 = self.pool.submit(self.portScanner,32800,36900)
        w10 = self.pool.submit(self.portScanner,36900,41000)
        w11= self.pool.submit(self.portScanner,41000,45100)
        w12 = self.pool.submit(self.portScanner,45100,49200)

        w13 = self.pool.submit(self.portScanner,49200,53300)
        w14 = self.pool.submit(self.portScanner,53300,57400)
        w15 = self.pool.submit(self.portScanner,57400,61500)
        w16 = self.pool.submit(self.portScanner,61500,65535)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
